src/device.cpp, src/ui/aboutdialog.h, src/ui/mainwindow.cpp
Fixing HOTP bug #27 
Tested on Ubuntu 15.04 with both Nitrokey Pro and Nitrokey Storage
Increased version to 0.3.1
Added some notes to code (fixmes and todos), small reformat
=> Fixing HOTP bug #27

nitrokey-app-qt5.pro
This reverts commit 2f6f9f4a5f5f263ed11236483a3796ce286d1d6d.
Reverting since it probably creates additional console window under
Windows.
@rudbo Is it ok for you?
=> Revert "Add console in CONFIG   += qt console"

src/ui/mainwindow.cpp
with random data into one operation
Issue #45
=> Combine generating AES keys and sd card initialization 

src/ui/mainwindow.cpp
=> Do not show empty passwords submenu

src/ui/mainwindow.cpp, src/ui/mainwindow.h, src/ui/stick20-response-task.cpp
Do not show tray messages during SD card clearing.
=> Issue 48 disable reconnecting while wiping

src/device.cpp, src/device.h, src/ui/mainwindow.cpp
Extend CLI with update mode and prodinfo sticks command.
Add disconnect for connection cleanup.
=> Extend CLI with stick update mode

src/device.cpp, src/ui/mainwindow.cpp, src/ui/mainwindow.h
Handle Factory Reset CLI command
Clean CLI handling code
=> Handle Factory Reset CLI command

src/device.cpp, src/device.h
=> Issue 82 Only first TOTP is valid when OTP is protected by user PIN

src/ui/mainwindow.cpp, src/ui/mainwindow.h
Tested on Ubuntu 16.04
Nitrokey Storage firmware version 0 35 0 6
=> Issue 45 NK Storage: Combine menu entries Generate Keys and Initialize Storage WIth Random Data 

src/ui/mainwindow.cpp
Fixes issue #78 and a compilation error for `HAVE_LIBAPPINDICATOR=ON`
=> Issue 78 only three passwords displayed

src/device.cpp
https://github.com/Nitrokey/nitrokey-storage-firmware/issues/12
Signed-off-by: Szczepan Zalega <szczepan@nitrokey.com>
=> Correct firmware password limit for update command

src/device.cpp
Signed-off-by: Szczepan Zalega <szczepan@nitrokey.com>
=> Allow firmware password to have at most CS20_MAX_UPDATE_PASSWORD_LEN

src/ui/mainwindow.cpp, src/ui/stick20changepassworddialog.cpp, src/ui/stick20changepassworddialog.h
Issue #68 
Tested on Ubuntu 16.04 with Nitrokey Pro 0.7
=> Issue 68 password feedback pro

coding-styles.sh
Make sure all modified files follows code format guidelines.
=> Code reformat only for modified files vs master branch

data/40-nitrokey.rules
Downloaded from main page: https://www.nitrokey.com/download
=> Update udev rules

CMakeLists.txt, data/nitrokey-app.desktop
=> 11 packaging related problems

src/device.cpp, src/device.h, src/main.cpp, src/response.cpp, src/ui/mainwindow.cpp, src/ui/mainwindow.h, ui/mainwindow.ui
#109 remember PIN for NK Pro while requesting PIN protected OTP
Fixes #109 and #144 
Ubuntu 16.04
NK Pro 0.7
NK Storage 0.40
=> remember PIN for NK Pro while requesting PIN protected OTP

src/command.cpp, src/command.h, src/device.cpp, src/main.cpp, src/response.cpp, src/ui/mainwindow.cpp, src/ui/mainwindow.h, src/ui/nitrokey-applet.cpp, src/ui/nitrokey-applet.h, src/ui/passworddialog.cpp, src/ui/passwordsafedialog.cpp, src/ui/pindialog.cpp, src/ui/stick20-response-task.cpp, src/ui/stick20changepassworddialog.cpp, src/ui/stick20dialog.cpp, src/ui/stick20hiddenvolumedialog.cpp, src/ui/stick20matrixpassworddialog.cpp, src/ui/stick20setup.cpp
Fixes #146 
In search for a cause of #142 a global code refactoring has been performed.
- move from heap to stack (use auto variables instead of new/delete)
- code simplifying
- take care of exact bytes copying (memcpy)
- use sizeof instead of hardcoded variables (for uin8_t)
- use agregate initialization instead of memset 
- make lazy initialized singleton from global variable (csApplet)
=> Code refactoring in an attempt to fix #142

src/ui/mainwindow.cpp
Fixes #138 . 
Refactoring only. Turned out application does not need any new modifications to make this work.
Checked with latest Storage firmware(v0.43) containing the proper fix.
Ubuntu 16.04
=> Refactoring: mainWindow::on_writeButton

i18n/nitrokey_de_DE.ts, i18n/nitrokey_en.ts, src/device.cpp, src/ui/mainwindow.cpp, src/ui/mainwindow.h
A workaround for #143 .
Tested on:
Windows 8.0, Qt 5.7, mingw32 (from Qt Creator 4.0.2), , NK Pro v0.7
$ ./g++ --version
g++.exe (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 5.3.0
=> Ask for device's reinsertion when its locked

i18n/nitrokey_de_DE.ts, i18n/nitrokey_en.ts, src/device.cpp, src/ui/mainwindow.cpp, src/ui/mainwindow.h
Tested on Ubuntu 16.04 with:
- Storage v0.43
- Pro v0.7
=> Warn user about secret starting from 0x00

CHANGELOG.md
With such file it will be easy to track changes between releases.
=> Add CHANGELOG.md generated with github-changelog-generator

src/main.cpp, src/ui/mainwindow.h
=> Add language CLI param

CMakeLists.txt, debian/changelog, src/ui/aboutdialog.h
=> Bump version to 0.6

resources.qrc
Missed Arabic translation file in resource file
=> Add Arabic translation to resource file

src/main.cpp
Instead of spawning config file in each working directory App was run
=> Use native settings handler

CHANGELOG.md, CMakeLists.txt, debian/changelog, src/ui/aboutdialog.h
=> Bump version to 0.6.1

src/ui/mainwindow.cpp
Partial fix for #211 
Tested with Pro 0.7, 0.8, Storage 0.43, Ubuntu 16.10
Precise tests would require running on Debian Jessie with mentioned in issue communication problems.
=> Break asking PIN loop when user cancels it

debian/rules
- remove executable on clean
- build on binary
- enable parallel build
=> Debian packaging rules changes

src/GUI/Authentication.cpp, src/GUI/StorageActions.cpp, src/ui/pindialog.cpp, src/ui/pindialog.h
=> Prompt user to change pin, while using default

src/GUI/Clipboard.cpp, src/GUI/Clipboard.h, src/main.cpp, src/ui/mainwindow.cpp, src/ui/mainwindow.h, src/ui/mainwindow.ui
=> Allow to change language from configuration window

i18n/nitrokey_de_DE.ts
=> Fixes #322

i18n/nitrokey_de_DE.ts, i18n/nitrokey_en.ts
Improve feedback information when requesting firmware export of NK Storage.
=> Add information about location of exported firmware file (fixes #363)

i18n/nitrokey_pl.ts
polish translation - corrected
=> nitrokey_pl.ts

i18n/nitrokey_pl.ts
Some corrections, explanation. need adjustments after seeing this release.
=> updates nitrokey_pl.ts after running new version

src/GUI/Tray.cpp, src/GUI/Tray.h, src/ui/aboutdialog.cpp
=> 370 delayed tray

i18n/nitrokey_pl.ts
Final update of Polish translation. Ready to go.
=> final update of nitrokey_pl.ts

src/ui/mainwindow.ui
* reduced minimal height of settings bottom-spacer to 0px (still expanding)
* reordered 4 settings items into 2
* expected overall height now ~750px
=> reducing minimum needed height of main window (#424)

CMakeLists.txt
=> Make BASH_COMPLETION_DIR user overridable

.gitlab-ci.yml
This should work right away, but it is not tested so let me know if there are any problems.
=> Enable automatic GitHub Release (nonsigned)
