- CMakeLists.txt
- src/systemutils.cpp
- src/ui/mainwindow.cpp
- systemutils.h
Should fix issue  Hidden volume is volatile #28.
Heavily tested on Ubuntu 15.04. 
Sync before changing devices is enabled for both Linux and  Mac. Unmounting code however is enabled only for Linux for now, until it will be tested on Mac.
> Fix for issue 28

- src/main.cpp
This is workaround for issue #43. It sets QT_QPA_PLATFORMTHEME to generic for local process if appmenu is detected within same variable. It should be sufficient for now. Bug is identified in Appmenu-qt5 and should be fixed within next versions of Ubuntu and / or it's package updates.
Fix works with Ubuntu 16.04 and Unity.
To cite from 'https://github.com/owncloud/client/issues/4693':
> Appmenu-qt5 is dead, and we want to remove it from Ubuntu as soon as our Qt is updated to 5.6 (which has native support for D-Bus trays and global menus). However, provided that 16.04 is an LTS release, it may make sense to get the appmenu-qt5 bug fixed there. I will add it to my list, however I have very few time, so I don't know when I will be able to get to it. Merge proposals against lp:appmenu-qt5 …
> Workaround for issue 43

- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
> Hiding "Lock device" from menu when no unlocked disks are available

- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
Fixes Issue #60 
Handling both Nitrokey Pro and Storage counters
> Issue 60 handle both firmwares for hotp

- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
Correcting solution for issue #45
Command "destroy encrypted data" should not initialize the storage with random data
Need to be tested yet.
> Correcting solution for issue #45

- src/device.cpp
- src/device.h
- src/ui/mainwindow.cpp
- src/ui/stick20changepassworddialog.cpp
- src/ui/stick20changepassworddialog.h
- ui/stick20changepassworddialog.ui
- ui/stick20updatedialog.ui
This is a fix for issue #38 
Fixed feedback for changing firmware, user and admin passwords for NK Storage.
Left to do:
- feedback for resetting user password
- feedback for setting update password
Tested on Ubuntu 16.04 with NK Storage.
> Issue 38 no feedback after changing password

- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
- src/ui/stick20-response-task.cpp
Reverts Nitrokey/nitrokey-app#70
Hotfix is not needed anymore since issue has been fixed on firmware side.
Check #70 and #48
> Revert "Issue 48 disable reconnecting messages while wiping"

- src/ui/mainwindow.cpp
Tested on Ubuntu 16.04 with 0.36 firmware
> Take status from device after AES keys initialization

- src/device.cpp
- src/ui/stick20changepassworddialog.cpp
Fix for issue #97 
Code enables proper feedback receiving from device
Tested on Ubuntu 16.04 and Windows 8.
There are some issues however with sub-sequential password changing, possibly caused by firmware (https://github.com/Nitrokey/nitrokey-storage-firmware/issues/11).
> Issue 97 firmware password feedback no debug

- .travis.yml
This PR is for test purposes and it's only task is to trigger Travis build for modified configuration on each `git push`. 
Since Travis internal update Nitrokey App stopped building because Ubuntu 12.04 Qt's package is renamed / removed from packages list apparently.
> Update travis configuration for application build

- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
Tested on Ubuntu 16.04
Fixed also bug with clearing empty clipboard every second after first code/secret request.
Clipboard not refactorized.
> Issue 54 clipboard clearing

- data/40-nitrokey.rules
> Add missing udev entry for Nitrokey Storage

- debian/changelog
- debian/control
- debian/postinst
- debian/rules
Changes added according to `Lintian`.
Should fix #115
> Adjust debian package creating script for launchpad.net

- debian/control
- debian/rules
Move package to universe and use qt5-base subcomponents instead of meta package.
> Build package on launchpad 2

- i18n/nitrokey_de_DE.ts
- i18n/nitrokey_en.ts
#150 
Merging translations from different branches causes many merge conflicts on file locations where the source text is located. To avoid it `lupdate -locations none` was applied to master branch and will be to every other ready to merge branch.
For work with QtLinguist one can reverse this effect with `lupdate -locations absolute` command.
> Remove locations from translation files

- i18n/nitrokey_de_DE.ts
- i18n/nitrokey_en.ts
- src/ui/mainwindow.cpp
- src/ui/stick20hiddenvolumedialog.cpp
- src/ui/stick20hiddenvolumedialog.h
- ui/stick20hiddenvolumedialog.ui
Fixes #72 
Tested on Ubuntu 16.04
- Adds visual password strength indicator
- Allows to input hidden volume size also in MB and GB (instead of only `%`)
- Fixed tab stops
- Improved general layout, added instructions and warnings
> Hidden setup usability fix

- src/ui/mainwindow.cpp
- ui/mainwindow.ui
Tested on Ubuntu 16.04
Nitrokey Storage v0.43
> Avoid buffer overflow during hex<->base32 conversion

- src/ui/mainwindow.cpp
Fixes #167 
FIxes #168 (typo)
Tested on Ubuntu 16.04, Pro v0.7, Storage v0.43
> Confirm erasing slot in Password Safe. Handle confirmation properly in OTP.

- CMakeLists.txt
Quite common setting is RelWithDebInfo, but here we allow only
Release / Debug which is not completely correct.
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> build: set CMAKE_BUILD_TYPE only if not set

- CMakeLists.txt
> Resolve conflict with udev rules (for Fedora 23)

- src/device.cpp
Fixes #214 
Tested on Windows 8.0:
- TOTP with random secret, sizes 30, 32, 60, 6 and 8 digits, secrets equal with 3rd party results
- HOTP with RFC secret, 6 and 8 digits, secrets equal the ones in example
Qt 5.7.0, MinGW 5.3.0
> Pack union for writing OTP slot data

- src/GUI/StorageActions.cpp
- src/systemutils.cpp
This PR should contain changes allowing to compile App on FreeBSD.
- Remove mntent.h
- Disable root-requiring code for automatic unmounting of the encrypted volume.
> FreeBSD compatible build

- src/GUI/ManageWindow.cpp
- src/ui/mainwindow.cpp
> Minor improvements

- CMakeLists.txt
The resources must be manually added to final executable in order to be built and liked.
ciao
luigi
> Compile and link resources to final executable

- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
…nstead call when required and we are sure that translation engine is configured.
The main issue is that we call tr() before that translation is configured, then we cannot translate these string after that.
>  ui/mainwindow: Don't call tr() and use QT_TRANSLATE_NOOP on global objects.

- i18n/nitrokey_de_DE.ts
> Use coherent translation of 'unlock'

- src/ui/mainwindow.cpp
```cxx
src/ui/mainwindow.cpp: In member function 'void MainWindow::PWS_ExceClickedSlot(int)':
src/ui/mainwindow.cpp:1454:9: warning: catching polymorphic type 'class DeviceCommunicationException' by value [-Wcatch-value=]
catch(DeviceCommunicationException){
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> fix build with -Wcatch-value=

- src/main.cpp
- src/ui/mainwindow.cpp
- src/ui/mainwindow.h
If the option --no-window is given the MainWindow is closed
immediately after it is shown. I have found no better solution for this.
Disclaimer: I am by no means a C++ or QT expert.
> Add option --no-window; workaround for #349

- data/com.nitrokey.nitrokey-app.appdata.xml
appstream-glib does not like it this way.
Closes: https://github.com/Nitrokey/nitrokey-app/issues/438
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> metainfo: Move 1.4.0 release to the top

- CMakeLists.txt
- data/nitrokey-app.1
This PR upstreams the manual page file created for the Debian package.
> Add manual page for nitrokey-app based on --help output.

- .gitlab-ci.yml
- ci-scripts/snapcraft.sh
All builds and auto-release now work: https://git.dotplex.com/nitrokey/nitrokey-app/-/pipelines/16112
- Image names corrected
- Fixed syntax error in ci-scripts/snapcraft.sh
> Ci - .gitlab-ci.yml fix image names (nitrokeyapp -> nitrokey-app)

- .gitlab-ci.yml
- ci-scripts/appimage.sh
ci fix - appimage: Remove old compatibility workaround - macos-dmg: allow failure and fix problems later
> ci fix - appimage: Remove old compatibility workaround
